### ISSUE TITLE
[Build fails] The vuex dependency leads to errors at building in Version 3.1.2

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wade#10]
# Comes up when
* npm install
* npm run electron:serve **OR** npm run electron:build

# Problem
When the `vuex` dependency is installed in Version 3.1.2 by npm, multiple Errors are thrown during building (depending on wade-branch around 60 errors). They all have a similar reason (difference is only the involved variable), an throw in different files, e.g.:
```
137:42 Property 'currentTabId' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, { id: unknown; getTdTabbar: any; }, Readonly<Record<never, any>>>'.
```

# Workaround
In package.json replace 
```json
vuex: "^3.1.1"
```
with
```json
vuex: "3.1.1"
```
then run `npm update vuex`. Now building should work.

# Fix
The workaround above is also applied to the ak_dev branch in [private Fork](https://gitlab.lrz.de/ga96jub/wade/commit/3480591107ff9f310c0e5f2630f596e26c571df2) and will be merged into the wade-master branch. Then the commit should be mentioned in this issue and the issue can be closed.

**Comment by egekorkan** [comment]
I think this can be closed now, what do you think @neniman ?

**Comment by Fady222** [comment]
I think we can close this for now, we can re-visit it if we change how we store things in W-ADE . What do you think @egekorkan?

**Comment by egekorkan** [comment]
yup the current way is not ideal but liveable... :)
