### ISSUE TITLE
[Sidebar] Del, Add, Merge Sidebar Elements needs a strict interface

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wade#14]
from Readme.md:
```
(+) Refactor: Deleting / Adding / Merging sidebar elements: strict interface to add / remove in data and in GUI 
```

**Comment by egekorkan** [comment]
@neniman Could you add some explanation to this issue? Do you mean the TS definitions by strict interface?

**Comment by neniman** [comment]
Actually I am also not sure what I meant with that.. so I'm closing this issue 😃
