### ISSUE TITLE
[Editor] Real JSON editor

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wade#27]
Atm the 'editor' in the TD interface of W-ADE is only a textarea. 
It should be replaced with a real JSON editor, including line numbers, collapsing lines, maybe highlighting.
This _real_ JSON editor needs to be compatible with vue.

**Comment by miguelrk** [comment]
Currently working on adding generic monaco editor component (for json, typescript, javascript, etc) with [vue-monaco](https://www.npmjs.com/package/vue-monaco)

![vue-monaco](https://user-images.githubusercontent.com/18708856/86134828-5d616900-baea-11ea-9399-176f2e83dba0.png)

**Comment by egekorkan** [comment]
Looks really nice! Could you already create a Draft PR?

**Comment by miguelrk** [comment]
@egekorkan I just created the draft PR. Editor works now and is implemented in every view where it should be, but it is throwing some WebWorker errors in the console. I'll keep looking into this.
