### ISSUE TITLE
[Dropdown] Hide all dropdowns if anything else was clicked

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wade#39]
Two initial thoughts:
* fire an event whenever the user clicks somewhere outside a dropdown and listen to it in `aDropdown`
* listen to the existing event `click` on document if possible?

**Comment by Fady222** [comment]
Another thought would be to close the menu when not in focus.

**Comment by neniman** [comment]
@Fady222 Dropdown buttons are also used in other components, that's why your idea unfortunately does not work.
