### ISSUE TITLE
Add prettyfier 

### ISSUE THREAD

**Issue by neniman** [tum-esi/wade#7]
Add some kind of code prettyfier.

**Comment by egekorkan** [comment]
Do you mean to restyle the source code?

**Comment by neniman** [comment]
> Do you mean to restyle the source code?

yes 🤓

**Comment by egekorkan** [comment]
Also being discussed in node-wot at https://github.com/eclipse/thingweb.node-wot/issues/239
I think we should also use editorconfig

**Comment by Fady222** [comment]
Isn't that already solved now? @egekorkan

**Comment by egekorkan** [comment]
YUP!
