### ISSUE TITLE
[URI Bar] CoAP TDs cannot be fetched

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wade#71]
As the is fetched using the `fetch` function at [this line](https://github.com/tum-esi/wade/blob/75b21210a9c7181e649c4fc943a74d8ee377ca77/src/components/04_templates/tThingDescription.vue#L119), it does not use the node-wot's fetch function that is actually protocol independent, see here ( https://github.com/eclipse/thingweb.node-wot/blob/6b207b0029654055f170f83dc94443cc8c94f956/packages/core/src/helpers.ts#L122 )

Also, there is no error displayed since there is no catch for the `fetch` function but only for the TD parsing. This is related to #40

**Comment by egekorkan** [comment]
Also valid for any other protocol

**Comment by Fady222** [comment]
Fixed in PR #98
