### ISSUE TITLE
[development] Add Vue CLI UI

### ISSUE THREAD

**Issue by miguelrk** [tum-esi/wade#84]
Vue CLI provides a built-in UI to manage the application (plugins, dependencies, devDependencies,etc). It is served locally and is very useful for development.

To be able to use it, a user must:

- Have Vue CLI globally installed: `npm install -g @vue/cli`

I therefore propose adding the following npm script to package.json:
```javascript
scripts: {
// ...
"ui": "vue ui"
}
```

This ways, users can run the corresponding npm script (package.json) during development: `npm run ui`.

![vue-cli-plugins-api](https://user-images.githubusercontent.com/18708856/87544356-93841880-c6a6-11ea-87e2-44411c7008b3.png)

**Comment by egekorkan** [comment]
I would support this. Just that we should not recommend installing it from npm but through your package manager and using the npm as a fallback. This would avoid dependency clashes.

**Comment by miguelrk** [comment]
Understood, it makes sense to not assume npm... will proceed to create a PR.

**Comment by egekorkan** [comment]
It is quite nice, available in master
